name: FSanitizer

on:
  workflow_dispatch:

jobs:
  fsanitize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile with AddressSanitizer
      run: |
        make clean
        make CFLAGS="-fsanitize=address,leak,undefined -g3"

    - name: Run tests with AddressSanitizer
      run: |
        ./minishell
